- name: Base setup for all servers
  hosts: netdienste:monitoring
  roles: []

- name: Network services (Kea DHCP)
  hosts: netdienste
  roles: [kea, exporters, restic]

- name: Monitoring server
  hosts: monitoring
  roles: [monitoring, restic]
